port: 8081
mongo:
  host: localhost
  port: 4000
  login:
  password:
  database: tasks-database
  collection: tasks
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: postgres


