GET http://localhost:{{port}}/task/example
#Content-Type: application/json
Accept: application/json

### save task
POST http://localhost:{{port}}/task
Content-Type: application/json

{
  "description": "test description111",
  "tags": ["from", "to"],
  "priority": "low"
}

### get all tasks
GET http://localhost:{{port}}/tasks
#Content-Type: application/json
Accept: application/json


###
GET http://localhost:{{port}}/task/63b41c5ff51e6b13b23b643a
#Content-Type: application/json
Accept: application/json

###
DELETE http://localhost:{{port}}/task/63b41c5ff51e6b13b23b643b
#Content-Type: application/json
Accept: text/plain

###
GET http://localhost:{{port}}/{{name}}
Accept: text/plain

###
PUT http://localhost:{{port}}/task
Content-Type: application/json


{
  "id": "6397ff14f6aa567f54d1bf35",
  "description": "updated task",
  "priority": "low",
  "tags": ["example", "plus"]
}


