GET http://localhost:{{port}}/task/example
#Content-Type: application/json
Accept: application/json

###
GET http://localhost:{{port}}/tasks
#Content-Type: application/json
Accept: text/plain

> {%
function t1() {

    // client.assert(
      // response.status === 200,
      // String(response.status)
      //      .concat(" is not 200")
  // )
}

client.test("request", t1);
%}

###
GET http://localhost:{{port}}/task/63b41c5ff51e6b13b23b643a
#Content-Type: application/json
Accept: application/json

###
DELETE http://localhost:{{port}}/task/63b41c5ff51e6b13b23b643b
#Content-Type: application/json
Accept: text/plain

###
GET http://localhost:{{port}}/{{name}}
Accept: text/plain

###
POST http://localhost:{{port}}/task
Content-Type: application/json

{
  "description": "test description123",
  "tags": null,
  "priority": "low"
}

###
PUT http://localhost:{{port}}/task
Content-Type: application/json


{
  "id": "6397ff14f6aa567f54d1bf35",
  "description": "updated task",
  "priority": "low",
  "tags": ["example", "plus"]
}


